c: idea

c: foo
	instanceOf	idea

c: bar
	instanceOf	idea
	
c: abuts
	instanceOf	slot
	inverseSlot	abuts

c: happy
	subOf	idea
	
c: sad
	subOf	idea
	
c: myExperiment
	instanceOf model
	actors		( ( foo ( foo1 ) true ) 
			  ( foo ( foo2 ) true ) 
			  ( bar ( bar1 ) true ) )
	relations	( ( abuts ( foo1 foo2 ) true ) 
			  ( abuts ( foo2 bar1 ) true ) )
	states		( ( happy ( foo2 ) true ) )
	
	
c: rule-1
	instanceOf	processRule
	ifActors	( ( foo ( *f1 ) true ) 
			  ( bar ( *b1 ) true ) 
			  ( foo ( *f2 ) true ) )
	ifRelations	( ( abuts ( *f2 *b1 ) true ) )
	ifNotStates	( ( sad ( *f1 ) true ) )
	thenStates	( ( sad ( *f1 ) true ) )
	thenSay		" Rule 1 fired "
	
c: rule-2
	instanceOf	processRule
	ifActors	( ( foo ( *f1 ) true ) 
			  ( bar ( *b1 ) true ) 
			  ( foo ( *f2 ) true ) )
	ifRelations	( ( abuts ( *f2 *b1 ) true ) )
	ifNotStates	( ( sad ( *b1 ) true ) )
	thenStates	( ( sad ( *b1 ) true ) )
	thenSay		" Rule 2 fired "

c: rule-3
	instanceOf	processRule
	ifActors	( ( foo ( *f1 ) true ) 
			  ( bar ( *b1 ) true ) 
			  ( foo ( *f2 ) true ) )
	ifRelations	( ( abuts ( *f1 *b1 ) true ) )
	ifNotStates	( ( sad ( *f2 ) true ) )
	thenStates	( ( sad ( *f2 ) true ) )
	thenSay		" Rule 3 fired "

c: task-1
	instanceOf	agendatask
	doTask		fillin
	onConcept	myExperiment
